ouvrir modifier
creer mine 80 150 -1 ROME
creer mine 150 150 9 BLEU_CLAIR
creer route 80 150 -1 ROME 150 150 9 BLEU_CLAIR 2
modifier mine posX 80 150 -1 ROME 500 
modifier mine posY 150 150 9 BLEU_CLAIR 80
creer mine 600 600 4 JAUNE
creer route 600 600 4 JAUNE 150 80 9 BLEU_CLAIR 1
fermer modifier
ouvrir jouer
selectionner SA
cliquer 150 150
cliquer 600 600


Choisir mine ROME -1, mine or 2
Choisir mine or 2, mine nickel 4
Choisir mine ROME, mine aluminium 6